hostname: nodenuvem4
rancher:
  console: debian
  docker:
    engine: docker-17.03.2-ce
  environment:
    EXTRA_CMDLINE: /init
  network:
    dns:
      nameservers:
      - 191.36.8.2
      - 191.36.8.3
      search:
      - sj.ifsc.edu.br
    interfaces:
      bond*:
        dhcp: false
      bond0:
        addresses:
        - 191.36.8.24/27
        bond_opts:
          downdelay: "200"
          lacp_rate: "1"
          miimon: "100"
          mode: "4"
          updelay: "200"
          xmit_hash_policy: layer2+3
        gateway: 191.36.8.30
      en*:
        dhcp: false
      eth*:
        dhcp: false
      mac=00:08:54:b3:6a:e9:
        bond: bond0
      mac=38:ea:a7:19:c5:87:
        bond: bond0
  services:
    user-volumes:
      volumes:
      - /home:/home
      - /opt:/opt
      - /var/lib/kubelet:/var/lib/kubelet
      - /etc/kubernetes:/etc/kubernetes
  services_include:
    kernel-extras: true
    volume-nfs: true
  state:
    dev: LABEL=RANCHER_STATE
    wait: true
  system:
    subnet: 169.254.25.1/16
  system_docker:
    bip: 169.254.25.1/16
runcmd:
- sudo apt update
- sudo apt install -y nfs-common
- sudo service rpcbind start
- sudo service nfs-common start
ssh_authorized_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAgEArgRS9p4JBq6CGuugYkf8PW7lejJpcJzDdjntND8wKhGUibkZRXcrxI40ClDEp7xLPzIzx6YSyV77AA16ers6AZs83FVSQY/sVO/qTXReyjHKJ1UhB3NQWsMI6XO+mcHFef50WLJ4rHd6b3A8swwF4XK4UtF8K6cDtJnJ1w4DmGwf3uAec0dUWF7UF4nP9VkTbH4bWETHPO7VXy5AcXx3rkzFF6+krtvrUHvC6QlzcUT0ofqb3mLBbWstaznE/lqXRFqHVwkkSLTy476qYM5286+UOTfTcwjsVCiohpoihPGWp4UE8ROKSmP8wLdYGHEJrB9k5FJGkZ5RjLhQ9ZIW9Dn/cgqFjOpvICe+26Zc7qaKTDp9vTCVkrZ94RV1e8gWlwbWcdNavuvpKcIxaNVmsxZ3RUiI5yewdGR3PCEbRkBiKq49E9cmitgbYWnn1jTQz9XXFSXL2MxRA4df6khmPZtKukvdjljt4jfbR40CZ5Q6VtJLO4yN7oYUWE+z3+YJtalT2VYO+L12phVAwjLlwn7JXijzXckBt6mCtTmQFCLBek/Y3EGdYpKnGLCfwvenpebxUOrhZFX8RJiHH8RQqUVv9LYtCdt88RdzAG15FlHufYQQHC+t2nZDrtW+XHpLBPgLFmbfDf03OIfIg/hxPwCDSPKqWgnpWJukdmuVze8= root@monitoramento
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCYymPFCq/EpbDr9Y5az6z6s3EO1WiiHboeyB94dKSplOG6GSddtwSu4WTr+QSPNks7farRQtAsQUi4j93fVD+T6Nt8k6nWLpbtUx2DLp17rsqi67RO1QixdywwcZwdYCaBztmaZlfPHVVC/rBXeonj8uz51AgpYrQCvnOXrCNWt6m7OpYn3b+AdUC3A3gu8b2KW7cmS1pLZMctfvAbMcFd93a4qO6J8J5dX/ZGG2o/l8Tt82GLGam+3x5Jyi6qa61RxHAbjibdo0WoSrQdGh0bU8twvaTi9bbdeOqa0UVdxDWfpAZY/HBxfRnb9FSVCb+BB9sDB3eyS0CC7KajFqe5 humbertos@sj-ctic-37246
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDQ7vlk1mQ4AZ/3AvstDmio9szcVlXA6LLX1lfgQoK5a1ob+K3wRBfEyVqsXqdAB8KGwDi4uRWTMMGYWklhHNRRTqLZj+RB1cIZWpVIEOU3GK/9DIbw0jc4J48h2ruUwnh5oqKeVT0xMU4Gdhsgp4hCSJBPJutBsm3ijJT8+9Qhp1FxK5C05h73KrbP0NWXOSV2XVqOVtt+9mF6pROa6z4+dI0HdjmsJEXgu7JOfSBQxOnmGd7ZosQc6T/Qxzwoq+qmmaojwDarvzsfPlgnpljd28xm2EicAuLKlvZs2Mz/0YW1NvwBHyq7TbX6FI+JU+qtNlVEmphhgrsthdBmU1v9Y0m3F5hSaKBym0kSVEH31k/EUglYj5Aop9kI+8hoNtDjCaXSPRY+xAqgS5PRb52+BeFfBqp7h+gTmh2qa4RZpa/zosgJUuQIAWI48s0izFIO5l997XY2soZ0/DBrYbkZAMgKBTF1L4/A8VlJdYVtJ6vwGx7YHnDkrWIO5BBtQxmG8Gi6jgoxCpT4tDuon+HcBLM0w0RuhF3QpmgKGDL9KesN6khwbMHEEpPhnuo6OFUu78uw9xiKgTcZ1PZxv/P5j8qoXNW02e5jWbXa/2al9YkO+O3YH+7YEft2hldJ4OF4S/AuicBjghCCnhCK2YWzhmdhNqkYoe7Ygo348aohFQ== marcelo.muniz@sj-lin-ctic-744529
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDHGABNL4VckVVEjgNJWrfFg6LqsypziY18hzVx12F/MA/q6RSJY7Wg/X5HRG7MKEdUezKCz7b6eSaTDP982Di1KD3YFLOnl8IJOf4fwxkwX7y7MX0xozDuJlhtMlJD8/g/n+hfybzsbQQkT0FC3onfOni7V8UfiNYq4wYNj6Vp0uj5eKNXUYeMe5yKLkCQa5r3pIH/4mTj/TF0pWMBjntTjxlstG7Z0a0r77UzMjFZAdGjfNfW3uSm3icyo1StIJ88I7WatJnhPDK3K7S/l8Ls+HU5tFh7AuPTVqPuiLtLEQ11XhcBKdIjewiGD6wfvyFVwCC94mWJnhS7rltIMYIFVZORgB5UuEUvZNevztyWhMb4Ho2Wi4jxSuU2If5huVRSmskeQe750E6FFWl1hB7XRDKGKbWHhG0BOCuB9h8wnpvn9s+7x1vvTdbnEx516JNyRGELtoElG20MYADou1N66yzusN/tdSeBO9BfvD6Sts/5HX8j0NNogF8swJ7DQEj0bbFoqBIeyfnJrQt+YJ85RuN/rexzYPYHEO6K7YR+u2cz4s5AJT9VCSVzVhG6ibj6RcBNCFTdok3qvAnwv5arvIuALeTZLVe+FFu5AKlJ2kQ+dtYqcXyeP5KyoHI2h5WzrxqTl/iOkoSFeTk+jt54DRGwP4kjBgGFdGeeNyzKmQ== rmartins@sj-lin-744396
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDm6baOg9AXEsNZCDwmIr32SEwfhoVvmT4WrsfMtJlPD5zfpGydC0oNbBtmB7DbwANSs79hCgsQw2SGgOumUQMPTCjdrK3DgpUuHZHnLbf/LdOvaM34HzVEwSJ8E24H3272ypdW9LxpNfDp3lwVv9UHQqc1pZ69nQkkEOq7OMozQD8inWDLhMfdXfkGtr8LwYV+Cq9H0jy+V5yAYkC5wMwf/uIVTwfocPZ4wn0iQTj6l/JVInb6A1RsxfhSbHtU+AXYxVa5zi/KJFSExkaIiuKYdTTN6/4jRJuwld7SdJ+f4c8Vh481WqisJCF339lGcVbfoTGdk7JwRNj/rWJrzBCZelVJxohB9eMC5yG6HFWQTb3CwboR6trQ0BK/pcwQMx90UlA8LEdNrGziO8djZIYvT4SWoZEwTe7Wq6s++YNkjs0Jjca+nK0xbci10zgApDUhWhArBdF0hIjVK22Q3g0HizpiwzTohcQfvMyIgrUmXXPAIbFF6Zit57PxzNQn9zHjz+eyznlIh119TnnbRnY7rYL9BT1sEqmb4lpl/H5H4iSfvVLsXrhWu3tXAkBFV1mUcSznfnjUJvLLPVY/p8dc5k4Ux57pOhuhwaGUC2UVjPGWRZw3hvcnqVESOPw8PduP/RWRz6xRH5BgO6YKRvvRhMtTp5+K7CSxgpBuCUcN3Q== boidacarapreta@gmail.com
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCxZ6W+iZn1dlWBBxLI3ZHup8LRGk4YpnynlG8Fm4oLdM/2fWKupyl8SJDity0m13AVQBMgpR2k/BA1HLFnWjPpxsjsA03ORTVFG3zGN8Yqb0LRuPfpXmQTQtVtGkN7FD4JKyzFeY+G4J0K3mVjOO2F8pGLvrota6q0/8fNfMsHt0uDZpC9c34qM6Xq72ZChJhnq4JY0QT6fzu2BmVnjDz4eBDlrsbtzdgkNF+z1jLdd4xSYgqFhUIrhU8Bsf6vGQMR0CRFh8huKaDCb4/y2F0NmIX0Y5ycwNfOHwvUoIYJMgv0bWv8Ewfg1MsEQ2MxN67H/4/zmMjo9jM7c40R7nmFwhm4pMMCpH8R7DoLAm4g1cKt80GXaef+7OBuluVcV6qOzaIMhBhOxjZomBgw/fjnUSjWrwJEHXNsAE8/gQLaM6OyMVl0L53FL1f8CuhQC618yge9DhM2yDw7IBxxteyA6Mp1GNPSx0HFFqisEZD0q7ZxW3PQMaTqM3Gdf+ONTP1tGbEirPn3YB3erqaYwirRNERcOpJqh/h9ahi8A9HLmSgOB0JGwKPS39ZBDU4OplIWhHY4QT6orzbrO/IkNXv7DxKQjt9N/kytVpP7MNgB6Mrepi4FDA2OUNKYCZ31c29SFOAUWjjd6K5r4W3JTbJtxVjME4/ifd6oQQHFdNIl2w== gabriel.souza@sj-ctic-29736

